// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: resource/definitions/security/security.proto

package security

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ImageVerificationConfigSpec represents the image verification configuration.
type ImageVerificationConfigSpec struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Rules         []*ImageVerificationRuleSpec `protobuf:"bytes,2,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageVerificationConfigSpec) Reset() {
	*x = ImageVerificationConfigSpec{}
	mi := &file_resource_definitions_security_security_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageVerificationConfigSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageVerificationConfigSpec) ProtoMessage() {}

func (x *ImageVerificationConfigSpec) ProtoReflect() protoreflect.Message {
	mi := &file_resource_definitions_security_security_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageVerificationConfigSpec.ProtoReflect.Descriptor instead.
func (*ImageVerificationConfigSpec) Descriptor() ([]byte, []int) {
	return file_resource_definitions_security_security_proto_rawDescGZIP(), []int{0}
}

func (x *ImageVerificationConfigSpec) GetRules() []*ImageVerificationRuleSpec {
	if x != nil {
		return x.Rules
	}
	return nil
}

// ImageVerificationRuleSpec represents a verification rule.
type ImageVerificationRuleSpec struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	ImagePattern  string                         `protobuf:"bytes,2,opt,name=image_pattern,json=imagePattern,proto3" json:"image_pattern,omitempty"`
	Verify        bool                           `protobuf:"varint,3,opt,name=verify,proto3" json:"verify,omitempty"`
	Verifier      *ImageVerificationVerifierSpec `protobuf:"bytes,4,opt,name=verifier,proto3" json:"verifier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageVerificationRuleSpec) Reset() {
	*x = ImageVerificationRuleSpec{}
	mi := &file_resource_definitions_security_security_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageVerificationRuleSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageVerificationRuleSpec) ProtoMessage() {}

func (x *ImageVerificationRuleSpec) ProtoReflect() protoreflect.Message {
	mi := &file_resource_definitions_security_security_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageVerificationRuleSpec.ProtoReflect.Descriptor instead.
func (*ImageVerificationRuleSpec) Descriptor() ([]byte, []int) {
	return file_resource_definitions_security_security_proto_rawDescGZIP(), []int{1}
}

func (x *ImageVerificationRuleSpec) GetImagePattern() string {
	if x != nil {
		return x.ImagePattern
	}
	return ""
}

func (x *ImageVerificationRuleSpec) GetVerify() bool {
	if x != nil {
		return x.Verify
	}
	return false
}

func (x *ImageVerificationRuleSpec) GetVerifier() *ImageVerificationVerifierSpec {
	if x != nil {
		return x.Verifier
	}
	return nil
}

// ImageVerificationRuleV1Alpha1 defines a verification rule.
type ImageVerificationRuleV1Alpha1 struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RuleImagePattern string                 `protobuf:"bytes,1,opt,name=rule_image_pattern,json=ruleImagePattern,proto3" json:"rule_image_pattern,omitempty"`
	RuleVerify       bool                   `protobuf:"varint,3,opt,name=rule_verify,json=ruleVerify,proto3" json:"rule_verify,omitempty"`
	RuleVerifier     *ImageVerifierV1Alpha1 `protobuf:"bytes,4,opt,name=rule_verifier,json=ruleVerifier,proto3" json:"rule_verifier,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ImageVerificationRuleV1Alpha1) Reset() {
	*x = ImageVerificationRuleV1Alpha1{}
	mi := &file_resource_definitions_security_security_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageVerificationRuleV1Alpha1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageVerificationRuleV1Alpha1) ProtoMessage() {}

func (x *ImageVerificationRuleV1Alpha1) ProtoReflect() protoreflect.Message {
	mi := &file_resource_definitions_security_security_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageVerificationRuleV1Alpha1.ProtoReflect.Descriptor instead.
func (*ImageVerificationRuleV1Alpha1) Descriptor() ([]byte, []int) {
	return file_resource_definitions_security_security_proto_rawDescGZIP(), []int{2}
}

func (x *ImageVerificationRuleV1Alpha1) GetRuleImagePattern() string {
	if x != nil {
		return x.RuleImagePattern
	}
	return ""
}

func (x *ImageVerificationRuleV1Alpha1) GetRuleVerify() bool {
	if x != nil {
		return x.RuleVerify
	}
	return false
}

func (x *ImageVerificationRuleV1Alpha1) GetRuleVerifier() *ImageVerifierV1Alpha1 {
	if x != nil {
		return x.RuleVerifier
	}
	return nil
}

// ImageVerificationVerifierSpec represents a signature verification provider.
type ImageVerificationVerifierSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Issuer        string                 `protobuf:"bytes,1,opt,name=issuer,proto3" json:"issuer,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	SubjectRegex  string                 `protobuf:"bytes,3,opt,name=subject_regex,json=subjectRegex,proto3" json:"subject_regex,omitempty"`
	RekorUrl      string                 `protobuf:"bytes,4,opt,name=rekor_url,json=rekorUrl,proto3" json:"rekor_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageVerificationVerifierSpec) Reset() {
	*x = ImageVerificationVerifierSpec{}
	mi := &file_resource_definitions_security_security_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageVerificationVerifierSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageVerificationVerifierSpec) ProtoMessage() {}

func (x *ImageVerificationVerifierSpec) ProtoReflect() protoreflect.Message {
	mi := &file_resource_definitions_security_security_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageVerificationVerifierSpec.ProtoReflect.Descriptor instead.
func (*ImageVerificationVerifierSpec) Descriptor() ([]byte, []int) {
	return file_resource_definitions_security_security_proto_rawDescGZIP(), []int{3}
}

func (x *ImageVerificationVerifierSpec) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *ImageVerificationVerifierSpec) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *ImageVerificationVerifierSpec) GetSubjectRegex() string {
	if x != nil {
		return x.SubjectRegex
	}
	return ""
}

func (x *ImageVerificationVerifierSpec) GetRekorUrl() string {
	if x != nil {
		return x.RekorUrl
	}
	return ""
}

// ImageVerifierV1Alpha1 configures a signature verification provider.
type ImageVerifierV1Alpha1 struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	KeylessIssuer       string                 `protobuf:"bytes,1,opt,name=keyless_issuer,json=keylessIssuer,proto3" json:"keyless_issuer,omitempty"`
	KeylessSubject      string                 `protobuf:"bytes,2,opt,name=keyless_subject,json=keylessSubject,proto3" json:"keyless_subject,omitempty"`
	KeylessSubjectRegex string                 `protobuf:"bytes,3,opt,name=keyless_subject_regex,json=keylessSubjectRegex,proto3" json:"keyless_subject_regex,omitempty"`
	KeylessRekorUrl     string                 `protobuf:"bytes,4,opt,name=keyless_rekor_url,json=keylessRekorUrl,proto3" json:"keyless_rekor_url,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ImageVerifierV1Alpha1) Reset() {
	*x = ImageVerifierV1Alpha1{}
	mi := &file_resource_definitions_security_security_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageVerifierV1Alpha1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageVerifierV1Alpha1) ProtoMessage() {}

func (x *ImageVerifierV1Alpha1) ProtoReflect() protoreflect.Message {
	mi := &file_resource_definitions_security_security_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageVerifierV1Alpha1.ProtoReflect.Descriptor instead.
func (*ImageVerifierV1Alpha1) Descriptor() ([]byte, []int) {
	return file_resource_definitions_security_security_proto_rawDescGZIP(), []int{4}
}

func (x *ImageVerifierV1Alpha1) GetKeylessIssuer() string {
	if x != nil {
		return x.KeylessIssuer
	}
	return ""
}

func (x *ImageVerifierV1Alpha1) GetKeylessSubject() string {
	if x != nil {
		return x.KeylessSubject
	}
	return ""
}

func (x *ImageVerifierV1Alpha1) GetKeylessSubjectRegex() string {
	if x != nil {
		return x.KeylessSubjectRegex
	}
	return ""
}

func (x *ImageVerifierV1Alpha1) GetKeylessRekorUrl() string {
	if x != nil {
		return x.KeylessRekorUrl
	}
	return ""
}

var File_resource_definitions_security_security_proto protoreflect.FileDescriptor

const file_resource_definitions_security_security_proto_rawDesc = "" +
	"\n" +
	",resource/definitions/security/security.proto\x12#talos.resource.definitions.security\"s\n" +
	"\x1bImageVerificationConfigSpec\x12T\n" +
	"\x05rules\x18\x02 \x03(\v2>.talos.resource.definitions.security.ImageVerificationRuleSpecR\x05rules\"\xb8\x01\n" +
	"\x19ImageVerificationRuleSpec\x12#\n" +
	"\rimage_pattern\x18\x02 \x01(\tR\fimagePattern\x12\x16\n" +
	"\x06verify\x18\x03 \x01(\bR\x06verify\x12^\n" +
	"\bverifier\x18\x04 \x01(\v2B.talos.resource.definitions.security.ImageVerificationVerifierSpecR\bverifier\"\xcf\x01\n" +
	"\x1dImageVerificationRuleV1Alpha1\x12,\n" +
	"\x12rule_image_pattern\x18\x01 \x01(\tR\x10ruleImagePattern\x12\x1f\n" +
	"\vrule_verify\x18\x03 \x01(\bR\n" +
	"ruleVerify\x12_\n" +
	"\rrule_verifier\x18\x04 \x01(\v2:.talos.resource.definitions.security.ImageVerifierV1Alpha1R\fruleVerifier\"\x93\x01\n" +
	"\x1dImageVerificationVerifierSpec\x12\x16\n" +
	"\x06issuer\x18\x01 \x01(\tR\x06issuer\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12#\n" +
	"\rsubject_regex\x18\x03 \x01(\tR\fsubjectRegex\x12\x1b\n" +
	"\trekor_url\x18\x04 \x01(\tR\brekorUrl\"\xc7\x01\n" +
	"\x15ImageVerifierV1Alpha1\x12%\n" +
	"\x0ekeyless_issuer\x18\x01 \x01(\tR\rkeylessIssuer\x12'\n" +
	"\x0fkeyless_subject\x18\x02 \x01(\tR\x0ekeylessSubject\x122\n" +
	"\x15keyless_subject_regex\x18\x03 \x01(\tR\x13keylessSubjectRegex\x12*\n" +
	"\x11keyless_rekor_url\x18\x04 \x01(\tR\x0fkeylessRekorUrlBz\n" +
	"+dev.talos.api.resource.definitions.securityZKgithub.com/siderolabs/talos/pkg/machinery/api/resource/definitions/securityb\x06proto3"

var (
	file_resource_definitions_security_security_proto_rawDescOnce sync.Once
	file_resource_definitions_security_security_proto_rawDescData []byte
)

func file_resource_definitions_security_security_proto_rawDescGZIP() []byte {
	file_resource_definitions_security_security_proto_rawDescOnce.Do(func() {
		file_resource_definitions_security_security_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_resource_definitions_security_security_proto_rawDesc), len(file_resource_definitions_security_security_proto_rawDesc)))
	})
	return file_resource_definitions_security_security_proto_rawDescData
}

var file_resource_definitions_security_security_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_resource_definitions_security_security_proto_goTypes = []any{
	(*ImageVerificationConfigSpec)(nil),   // 0: talos.resource.definitions.security.ImageVerificationConfigSpec
	(*ImageVerificationRuleSpec)(nil),     // 1: talos.resource.definitions.security.ImageVerificationRuleSpec
	(*ImageVerificationRuleV1Alpha1)(nil), // 2: talos.resource.definitions.security.ImageVerificationRuleV1Alpha1
	(*ImageVerificationVerifierSpec)(nil), // 3: talos.resource.definitions.security.ImageVerificationVerifierSpec
	(*ImageVerifierV1Alpha1)(nil),         // 4: talos.resource.definitions.security.ImageVerifierV1Alpha1
}
var file_resource_definitions_security_security_proto_depIdxs = []int32{
	1, // 0: talos.resource.definitions.security.ImageVerificationConfigSpec.rules:type_name -> talos.resource.definitions.security.ImageVerificationRuleSpec
	3, // 1: talos.resource.definitions.security.ImageVerificationRuleSpec.verifier:type_name -> talos.resource.definitions.security.ImageVerificationVerifierSpec
	4, // 2: talos.resource.definitions.security.ImageVerificationRuleV1Alpha1.rule_verifier:type_name -> talos.resource.definitions.security.ImageVerifierV1Alpha1
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_resource_definitions_security_security_proto_init() }
func file_resource_definitions_security_security_proto_init() {
	if File_resource_definitions_security_security_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_resource_definitions_security_security_proto_rawDesc), len(file_resource_definitions_security_security_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_resource_definitions_security_security_proto_goTypes,
		DependencyIndexes: file_resource_definitions_security_security_proto_depIdxs,
		MessageInfos:      file_resource_definitions_security_security_proto_msgTypes,
	}.Build()
	File_resource_definitions_security_security_proto = out.File
	file_resource_definitions_security_security_proto_goTypes = nil
	file_resource_definitions_security_security_proto_depIdxs = nil
}
