// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

// Code generated by "deep-copy -type ImageVerificationConfigSpec -header-file ../../../../hack/boilerplate.txt -o deep_copy.generated.go ."; DO NOT EDIT.

package security

// DeepCopy generates a deep copy of ImageVerificationConfigSpec.
func (o ImageVerificationConfigSpec) DeepCopy() ImageVerificationConfigSpec {
	var cp ImageVerificationConfigSpec = o
	if o.Rules != nil {
		cp.Rules = make([]ImageVerificationRuleSpec, len(o.Rules))
		copy(cp.Rules, o.Rules)
		for i2 := range o.Rules {
			if o.Rules[i2].Verifier != nil {
				cp.Rules[i2].Verifier = new(ImageVerificationVerifierSpec)
				*cp.Rules[i2].Verifier = *o.Rules[i2].Verifier
			}
		}
	}
	return cp
}
